export const FIREBASE_ADMIN_TOKEN = 'FIREBASE_ADMIN_TOKEN';

export const FIREBASE_CONFIG_KEY = {
  PROJECT_ID: 'FIREBASE_PROJECT_ID',
  CREDENTIAL_SOURCE: 'FIREBASE_CREDENTIAL_SOURCE',
  SERVICE_ACCOUNT_KEY_PATH: 'FIREBASE_SERVICE_ACCOUNT_KEY_PATH',
  SERVICE_ACCOUNT_JSON: 'FIREBASE_SERVICE_ACCOUNT_JSON',
};

export enum FIREBASE_CREDENTIAL_SOURCE {
  FILE = 'file',
  JSON = 'json',
  DEFAULT = 'default',
}
