/**
 * Application Error Codes
 * Following Mori-Planning pattern
 */

export const ERROR_CODES = {
  // Common
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_EMAIL_SERVICE_UNAVAILABLE: 'OTP_EMAIL_SERVICE_UNAVAILABLE',
  OTP_INVALID_OR_EXPIRED: 'OTP_INVALID_OR_EXPIRED',
  OTP_PENDING_DATA_NOT_FOUND: 'OTP_PENDING_DATA_NOT_FOUND',
  
  // Clinics
  CLINIC_NOT_FOUND: 'CLINIC_NOT_FOUND',
  
  // Doctors
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  
  // Packages
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  
  // Bookings
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  INVALID_BOOKING_TIME: 'INVALID_BOOKING_TIME',
  INVALID_CLINIC: 'INVALID_CLINIC',
  CLINIC_CLOSED: 'CLINIC_CLOSED',
  INVALID_DOCTOR: 'INVALID_DOCTOR',
  INVALID_BOOKING_DATE: 'INVALID_BOOKING_DATE',
  INVALID_PATIENT_DOB: 'INVALID_PATIENT_DOB',
  BOOKING_CANNOT_BE_CANCELLED: 'BOOKING_CANNOT_BE_CANCELLED',
  BOOKING_CANNOT_BE_RESCHEDULED: 'BOOKING_CANNOT_BE_RESCHEDULED',
  BOOKING_SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_IN_THE_PAST: 'BOOKING_IN_THE_PAST',
  
  // Articles
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',

  // Validation
  INVALID_DATE: 'INVALID_DATE',
  INVALID_TIME_FORMAT: 'INVALID_TIME_FORMAT',
};
