export const ADMIN_DAY_OPTIONS = [
    { value: 0, label: "Chủ nhật" },
    { value: 1, label: "Thứ 2" },
    { value: 2, label: "Thứ 3" },
    { value: 3, label: "Thứ 4" },
    { value: 4, label: "Thứ 5" },
    { value: 5, label: "Thứ 6" },
    { value: 6, label: "Thứ 7" },
] as const

export const ADMIN_TEXT = {
    common: {
        loading: "Đang tải...",
        rolePrefix: "Vai trò",
        logout: "Đăng xuất",
        backHome: "Về trang chủ",
        goAccount: "Đến trang tài khoản",
        close: "Đóng",
        edit: "Sửa",
        delete: "Xóa",
        cancelEdit: "Hủy chỉnh sửa",
        confirm: "Xác nhận",
        save: "Lưu",
        saving: "Đang lưu...",
        update: "Cập nhật",
        updating: "Đang cập nhật...",
        add: "Thêm",
        adding: "Đang thêm...",
        create: "Tạo",
    },
    accessDenied: {
        title: "403 - Không có quyền truy cập",
        description: "Tài khoản bệnh nhân không thể truy cập trang quản trị.",
    },
    topBar: {
        title: "Trung tâm quản trị Healthcare",
    },
    roles: {
        admin: "Quản trị viên",
        doctor: "Bác sĩ",
        clinicAdmin: "Quản trị phòng khám",
        patient: "Bệnh nhân",
        unknown: "Không xác định",
    },
    bookingStatus: {
        pending: "Chờ xác nhận",
        confirmed: "Đã xác nhận",
        completed: "Đã hoàn tất",
        cancelled: "Đã hủy",
    },
    bookingTable: {
        patient: "Bệnh nhân",
        date: "Ngày khám",
        time: "Giờ khám",
        status: "Trạng thái",
        actions: "Thao tác",
    },
    doctorAdmin: {
        stats: {
            total: "Tổng lịch khám",
            pending: "Chờ xác nhận",
            confirmed: "Đã xác nhận",
            completed: "Đã hoàn tất",
        },
        tabs: {
            bookings: "Lịch khám bệnh nhân",
            schedule: "Lịch làm việc",
            services: "Dịch vụ và giá",
        },
        pendingCard: {
            title: "Xác nhận lịch khám đang chờ",
            description: "Bệnh nhân đặt lịch sẽ ở trạng thái chờ. Bác sĩ xác nhận thì lịch mới hoàn tất.",
            empty: "Hiện không có lịch nào đang chờ xác nhận.",
            confirm: "Xác nhận",
            reject: "Từ chối",
        },
        allCard: {
            title: "Tất cả lịch khám",
            description: "Theo dõi toàn bộ trạng thái lịch khám của bạn",
            filterPlaceholder: "Lọc trạng thái",
            filters: {
                all: "Tất cả trạng thái",
                pending: "Chờ xác nhận",
                confirmed: "Đã xác nhận",
                completed: "Đã hoàn tất",
                cancelled: "Đã hủy",
            },
            empty: "Không có dữ liệu lịch khám phù hợp bộ lọc.",
            confirm: "Xác nhận",
            complete: "Hoàn tất",
            cancel: "Hủy",
        },
        scheduleCard: {
            title: "Thiết lập lịch khám theo ngày trong tuần",
            description: "Bạn có thể bật/tắt từng ngày, điều chỉnh giờ bắt đầu - kết thúc và thời lượng mỗi slot.",
            slotDurationLabel: "Thời lượng mỗi slot (phút)",
            headers: {
                day: "Ngày",
                enabled: "Bật lịch",
                start: "Giờ bắt đầu",
                end: "Giờ kết thúc",
            },
            save: "Lưu lịch làm việc",
        },
        scheduleError: "Cần chọn ít nhất 1 ngày làm việc trong tuần.",
        servicesCard: {
            title: "Dịch vụ khám và giá",
            description: "Cập nhật danh sách dịch vụ để bệnh nhân xem trước khi đặt lịch.",
            empty: "Chưa có dịch vụ nào. Hãy thêm dịch vụ đầu tiên.",
            nameLabel: "Tên dịch vụ",
            namePlaceholder: "VD: Khám tổng quát, Siêu âm...",
            priceLabel: "Giá dịch vụ",
            pricePlaceholder: "Nhập giá tiền...",
            currencyLabel: "Tiền tệ",
            currencyPlaceholder: "VND",
            remove: "Xóa dịch vụ",
            add: "Thêm dịch vụ",
            save: "Lưu bảng giá",
        },
        cancelDialog: {
            title: "Xác nhận hủy lịch hẹn",
            descriptionPrefix: "Hành động này sẽ hủy lịch của bệnh nhân",
            descriptionSuffix: ". Vui lòng kiểm tra kỹ trước khi xác nhận.",
            dateLabel: "Ngày khám",
            timeLabel: "Giờ khám",
            reasonLabel: "Lý do hủy (không bắt buộc)",
            reasonPlaceholder: "Nhập lý do để bệnh nhân nắm thông tin...",
            back: "Quay lại",
            confirm: "Xác nhận hủy",
            confirming: "Đang hủy...",
        },
    },
    clinicAdmin: {
        clinicFallback: "Phòng khám",
        headerDescription: "Quản lý giờ hoạt động phòng khám, slot gói khám và xác nhận lịch gói khám.",
        workingHours: {
            title: "Giờ hoạt động phòng khám",
            openLabel: "Mở",
            save: "Lưu giờ phòng khám",
        },
        specialtySchedule: {
            title: "Lịch và slot theo chuyên khoa",
            description: "Bác sĩ và gói khám sẽ bám theo lịch này, vì vậy slot không bị lệch giữa phòng khám và bác sĩ.",
            selectLabel: "Chọn chuyên khoa",
            selectPlaceholder: "Chọn chuyên khoa",
            configuringPrefix: "Đang cấu hình",
            slotDurationLabel: "Thời lượng mỗi slot chuyên khoa",
            slotDurationOptions: {
                thirty: "30 phút",
                sixty: "60 phút",
            },
            capacityLabel: "Sức chứa mỗi slot",
            activeLabel: "Bật",
            save: "Lưu lịch chuyên khoa",
        },
        packages: {
            title: "Gói khám và slot gói khám",
            description: "Gói khám thuộc phòng khám và chuyên khoa, có thể bật/tắt hoạt động và đặt sức chứa riêng.",
            nameLabel: "Tên gói",
            descriptionLabel: "Mô tả",
            priceLabel: "Giá",
            namePlaceholder: "Gói khám tổng quát",
            descriptionPlaceholder: "Mô tả ngắn",
            create: "Tạo gói",
            specialtyFallback: "Chưa gán chuyên khoa",
            activeLabel: "Hoạt động",
            selectLabel: "Chọn gói khám",
            selectPlaceholder: "Chọn gói khám",
            saveAvailability: "Lưu slot gói khám",
        },
        bookings: {
            title: "Lịch đặt gói khám",
            headers: {
                patient: "Bệnh nhân",
                package: "Gói khám",
                dateTime: "Ngày giờ",
                status: "Trạng thái",
                actions: "Thao tác",
            },
            confirm: "Xác nhận",
            cancel: "Hủy",
            complete: "Hoàn tất",
        },
        specialtyFallback: "chuyên khoa",
    },
    packageAdmin: {
        titleCreate: "Tạo gói khám",
        titleUpdate: "Cập nhật gói khám",
        description: "Mỗi gói khám bắt buộc gắn với một phòng khám để giá và nội dung không bị nhầm lẫn.",
        labels: {
            clinic: "Phòng khám",
            specialty: "Chuyên khoa",
            name: "Tên gói",
            category: "Danh mục",
            price: "Giá niêm yết",
            promotionalPrice: "Giá ưu đãi",
            shortDescription: "Mô tả ngắn",
            description: "Mô tả chi tiết",
            features: "Dịch vụ trong gói, mỗi dòng một mục",
            image: "Link ảnh",
        },
        placeholders: {
            clinic: "Chọn phòng khám",
            specialty: "Chọn chuyên khoa của phòng khám",
            name: "Gói khám tổng quát",
            category: "general",
        },
        switches: {
            popular: "Hiển thị nổi bật",
            active: "Đang mở bán",
        },
        buttons: {
            update: "Cập nhật",
            create: "Tạo gói khám",
            cancelEdit: "Hủy sửa",
            edit: "Sửa",
            delete: "Xóa",
        },
        listTitle: "Danh sách gói khám",
        tableHeaders: {
            package: "Gói khám",
            clinic: "Phòng khám",
            specialty: "Chuyên khoa",
            price: "Giá",
            status: "Trạng thái",
            actions: "Thao tác",
        },
        status: {
            active: "Đang mở",
            inactive: "Đang ẩn",
            popular: "Nổi bật",
        },
        currencySuffix: "đ",
    },
    systemAdminV2: {
        stats: {
            users: "Tài khoản",
            doctors: "Tài khoản bác sĩ",
            openClinics: "Phòng khám mở",
            articles: "Bài cẩm nang",
        },
        tabs: {
            users: "Người dùng",
            clinics: "Phòng khám",
            doctors: "Bác sĩ",
            packages: "Gói khám",
            news: "Cẩm nang",
        },
        users: {
            title: "Tạo tài khoản quản trị phòng khám",
            description: "Quản trị phòng khám quản lý giờ phòng khám, slot gói khám và xác nhận đặt lịch gói khám.",
            placeholders: {
                name: "Họ tên",
                email: "Email",
                phone: "Số điện thoại",
                password: "Mật khẩu",
            },
            selectClinicPlaceholder: "Chọn phòng khám",
            createButton: "Tạo quản trị phòng khám",
            listTitle: "Danh sách người dùng",
            searchPlaceholder: "Tìm theo tên, email, SĐT",
            roleFilters: {
                all: "Tất cả vai trò",
                patient: "Bệnh nhân",
                doctor: "Bác sĩ",
                clinicAdmin: "Quản trị phòng khám",
            },
            headers: {
                name: "Họ tên",
                email: "Email",
                phone: "Điện thoại",
                role: "Vai trò",
                status: "Trạng thái",
                actions: "Thao tác",
            },
            status: {
                active: "Đang hoạt động",
                locked: "Đã khóa",
            },
            actions: {
                lock: "Khóa",
                unlock: "Mở",
                delete: "Xóa",
            },
        },
        clinics: {
            listTitle: "Danh sách phòng khám",
            listDescription: "Bấm Sửa để chỉnh thông tin bằng popup.",
            addButton: "Thêm phòng khám",
            headers: {
                clinic: "Phòng khám",
                specialty: "Chuyên khoa",
                contact: "Liên hệ",
                status: "Trạng thái",
                actions: "Thao tác",
            },
            specialtyFallback: "Chưa thiết lập",
            status: {
                open: "Đang mở",
                closed: "Tạm đóng",
            },
        },
        doctors: {
            listTitle: "Danh sách bác sĩ",
            listDescription: "Tạo mới, sửa hồ sơ, tạm nghỉ hoặc xóa bác sĩ.",
            addButton: "Tạo tài khoản bác sĩ",
            headers: {
                avatar: "Ảnh",
                doctor: "Bác sĩ",
                clinic: "Phòng khám",
                specialty: "Chuyên khoa",
                experience: "Kinh nghiệm",
                status: "Trạng thái",
                actions: "Thao tác",
            },
            accountFallback: "Chưa liên kết tài khoản",
            experienceSuffix: "năm",
            status: {
                available: "Sẵn sàng",
                off: "Tạm nghỉ",
            },
            actions: {
                edit: "Sửa",
                disable: "Tạm nghỉ",
                enable: "Mở khám",
                delete: "Xóa",
            },
        },
        news: {
            titleCreate: "Thêm bài cẩm nang",
            titleUpdate: "Cập nhật bài cẩm nang",
            description: "Quản lý nội dung cẩm nang sức khỏe trên website.",
            placeholders: {
                title: "Tiêu đề",
                category: "Chuyên mục",
                readTime: "Thời gian đọc",
                image: "Link ảnh đại diện",
                description: "Mô tả nội dung",
            },
            createButton: "Thêm bài viết",
            updateButton: "Cập nhật bài viết",
            listTitle: "Danh sách cẩm nang",
            headers: {
                title: "Tiêu đề",
                category: "Chuyên mục",
                readTime: "Thời gian đọc",
                actions: "Thao tác",
            },
        },
        clinicDialog: {
            titleCreate: "Thêm phòng khám",
            titleUpdate: "Sửa phòng khám",
            description: "Nhập đầy đủ thông tin phòng khám và các chuyên khoa đang cung cấp.",
            labels: {
                name: "Tên phòng khám",
                address: "Địa chỉ",
                phone: "Số điện thoại",
                email: "Email",
                website: "Website",
                openingHours: "Giờ mở cửa",
                image: "Link ảnh phòng khám",
                description: "Mô tả phòng khám",
                specialty: "Chuyên khoa",
                open: "Đang mở cửa",
            },
            buttons: {
                create: "Thêm phòng khám",
            },
        },
        doctorDialog: {
            titleCreate: "Tạo tài khoản bác sĩ",
            titleUpdate: "Sửa hồ sơ bác sĩ",
            description: "Tài khoản đăng nhập và hồ sơ chuyên môn được lưu cùng lúc để bác sĩ xuất hiện ngay trong danh sách.",
            sections: {
                account: "Thông tin tài khoản",
                profile: "Thông tin chuyên môn",
            },
            labels: {
                name: "Họ tên bác sĩ",
                email: "Email đăng nhập",
                phone: "Số điện thoại",
                password: "Mật khẩu",
                clinic: "Phòng khám",
                specialty: "Chuyên khoa",
                experience: "Số năm kinh nghiệm",
                avatar: "Link ảnh đại diện",
                bio: "Giới thiệu bác sĩ",
                available: "Sẵn sàng nhận lịch",
            },
            placeholders: {
                clinic: "Chọn phòng khám",
                specialty: "Chọn chuyên khoa",
            },
            buttons: {
                create: "Tạo tài khoản bác sĩ",
            },
            createPending: "Đang tạo...",
        },
    },
    systemAdminLegacy: {
        stats: {
            totalUsers: "Tổng tài khoản",
            doctors: "Tài khoản bác sĩ",
            openClinics: "Phòng khám mở",
            articles: "Bài cẩm nang",
        },
        tabs: {
            users: "Người dùng",
            clinics: "Phòng khám",
            doctors: "Bác sĩ",
            news: "Cẩm nang",
        },
        users: {
            createDoctorTitle: "Tạo tài khoản bác sĩ",
            createDoctorDescription: "Tài khoản bệnh nhân tự đăng ký ở trang người dùng. Tại đây chỉ tạo tài khoản bác sĩ.",
            createDoctorButton: "Tạo tài khoản bác sĩ",
            listDescription: "Quản lý trạng thái hoạt động của tài khoản.",
            filterPlaceholder: "Lọc vai trò",
            roleFilters: {
                all: "Tất cả vai trò",
                doctor: "Bác sĩ",
                patient: "Bệnh nhân",
                admin: "Quản trị viên",
            },
            empty: "Không có người dùng phù hợp.",
        },
        clinics: {
            titleCreate: "Thêm phòng khám mới",
            titleUpdate: "Cập nhật phòng khám",
            description: "Bổ sung đủ thông tin hiển thị cho bệnh nhân: ảnh, địa chỉ, giờ hoạt động, liên hệ.",
            headers: {
                avatar: "Ảnh",
                name: "Tên phòng khám",
                contact: "Liên hệ",
                hours: "Giờ hoạt động",
                status: "Trạng thái",
                actions: "Thao tác",
            },
            placeholders: {
                name: "Tên phòng khám",
                address: "Địa chỉ",
                phone: "Số điện thoại",
                email: "Email",
                website: "Website",
                openingHours: "Giờ làm việc (ví dụ: 08:00 - 17:00)",
                image: "Link ảnh đại diện phòng khám",
                description: "Mô tả ngắn phòng khám",
            },
            openLabel: "Phòng khám đang mở",
            listDescription: "Bật/tắt hoạt động, chỉnh sửa thông tin hoặc xóa phòng khám.",
            empty: "Chưa có phòng khám nào.",
            toggleClose: "Đóng",
            toggleOpen: "Mở",
        },
        doctors: {
            titleCreate: "Thêm hồ sơ bác sĩ",
            titleUpdate: "Cập nhật hồ sơ bác sĩ",
            description: "Hồ sơ bác sĩ gồm tài khoản, chuyên khoa, phòng khám, ảnh đại diện, mô tả kinh nghiệm.",
            submitCreate: "Thêm bác sĩ",
            submitUpdate: "Cập nhật bác sĩ",
            placeholders: {
                name: "Tên bác sĩ",
                linkAccount: "Liên kết tài khoản bác sĩ",
                clinic: "Chọn phòng khám",
                specialty: "Chọn chuyên khoa",
                experience: "Số năm kinh nghiệm",
                avatar: "Link ảnh đại diện bác sĩ",
                bio: "Giới thiệu bác sĩ",
            },
            availableLabel: "Sẵn sàng nhận khám",
            listDescription: "Quản lý hồ sơ, chuyên khoa, phòng khám và trạng thái khám.",
            empty: "Chưa có hồ sơ bác sĩ.",
        },
        news: {
            description: "Bài viết cẩm nang để bệnh nhân đọc trước/sau khi đặt lịch khám.",
            placeholders: {
                readTime: "Thời gian đọc (ví dụ: 5 phút)",
                image: "Link ảnh đại diện bài viết",
            },
            headers: {
                publishedAt: "Ngày đăng",
            },
            empty: "Chưa có bài viết nào.",
        },
        summary: {
            title: "Tóm tắt vận hành",
            description: "Gợi ý luồng: tạo tài khoản bác sĩ ở tab Người dùng, sau đó tạo hồ sơ chuyên môn ở tab Bác sĩ.",
            steps: {
                accountTitle: "1. Tài khoản bác sĩ",
                accountDescription: "Tạo email/mật khẩu để bác sĩ đăng nhập vào trang quản trị.",
                profileTitle: "2. Hồ sơ bác sĩ",
                profileDescription: "Gán bác sĩ vào phòng khám + chuyên khoa + ảnh đại diện + thông tin kinh nghiệm.",
                workflowTitle: "3. Bác sĩ nhận lịch",
                workflowDescription: "Bác sĩ xác nhận lịch chờ và thiết lập lịch làm việc/giá dịch vụ trực tiếp trong tài khoản của họ.",
            },
        },
    },
} as const
